version: 2
jobs:
  build:
    docker:
        - image: circleci/node:8.11-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "server/package.json" }}
          # fallback to using the latest cache if no exact match is found

      - run: cd server && npm install --production

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}
        
      - run: npm run build

