version: 2
jobs:
  build_app:
    docker:
        - image: circleci/node:8.11-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "server/package.json" }}
          # fallback to using the latest cache if no exact match is found

      - run: cd server && npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "server/package.json" }}
        
      - run: cd server && npm run build

      - persist_to_workspace:
              root: ~/repo
              paths:
                - build

  build_docker:
      docker:
       - image: circleci/node:8.11-stretch
      steps:
        - setup_remote_docker

        - attach_workspace:
            at: ~/repo
        - run:
            name: docker build
            command: |
              export PACKAGE_VERSION=$(sed -nE 's/^\s*"version": "(.*?)",$/\1/p' package.json)
              docker login -u $DOCKER_REPO_USR -p $DOCKER_REPO_PWD
              docker build -t zappatta/wremote:latest ./
              docker tag zappatta/wremote:latest zappatta/wremote:$PACKAGE_VERSION
              docker push zappatta/wremote:latest
              docker push zappatta/wremote:$PACKAGE_VERSION


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_app
      - build_docker:
          requires:
            - build_app