name: Node.js CI

on: [push]

jobs:
  build:
    defaults:
      run:
        working-directory: web-app/client

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm ci
    - name: build
      run: npm run build --if-present
    - name: test
      run: npm test
      env:
        CI: true
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FOLDER: dist # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
