name: Test

on: [push]

jobs:
  test:
    defaults:
      run:
        working-directory: web-app/client

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.18]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm ci
      - name: test
        run: npm test
        env:
          CI: true
